name: medicalreminder
description: medical reminder app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.3
  cima_repository:
    path: packages/cima_repository
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  intl: ^0.17.0
  url_launcher: any

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
