name: authentication_repository
description: Authentication repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.11
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  json_annotation: any

dev_dependencies:
  build_runner: any
  coverage: ^1.1.0
  flutter_test:
    sdk: flutter
  json_serializable: any
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

