name: cima_model
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: any
  json_annotation: any

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: ^1.17.0
  very_good_analysis: ^2.4.0
