name: medicalreminder

on: [pull_request, push]

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      flutter_channel: stable
      flutter_version: 2.10.0
      test_recursion: true
      min_coverage: 1
      token: "${{secrets.CODECOV_TOKEN}}"
